# Generated by Django 5.2.5 on 2025-09-05 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'default_related_name': 'recipes', 'ordering': ['-pub_date'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_name_measurement_unit', violation_error_message='Ингредиент с таким названием и единицей измерения уже существует.'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient', violation_error_message='Этот ингредиент уже добавлен к рецепту.'),
        ),
        migrations.AlterConstraint(
            model_name='favorite',
            name='unique_favorite_user_recipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorite_user_recipe', violation_error_message='Этот рецепт уже добавлен в избранное.'),
        ),
        migrations.AlterConstraint(
            model_name='shoppingcart',
            name='unique_shopping_cart_user_recipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_shopping_cart_user_recipe', violation_error_message='Этот рецепт уже добавлен в список покупок.'),
        ),
        migrations.AlterConstraint(
            model_name='subscription',
            name='unique_subscriber_subscribing',
            constraint=models.UniqueConstraint(fields=('subscriber', 'subscribing'), name='unique_subscriber_subscribing', violation_error_message='Нельзя подписаться на одного и того же пользователя дважды.'),
        ),
    ]
