# Generated by Django 5.2.5 on 2025-09-08 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_shopping_cart_user_recipe',
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_shoppingcart_user_recipe', violation_error_message='Этот рецепт уже добавлен.'),
        ),
        migrations.AlterConstraint(
            model_name='favorite',
            name='unique_favorite_user_recipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorite_user_recipe', violation_error_message='Этот рецепт уже добавлен.'),
        ),
    ]
